arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
output-dir: lib/l10n
preferred-supported-locales: [en, pt, es, de, fr, it]
synthetic-package: false
untranslated-messages-file: untranslated.txt