name: a_chess_time
description: "A modern and intuitive chess timer app with customizable time controls, themes, and multilingual support."
publish_to: 'none'
version: 2.0.0+18
environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  google_fonts: ^6.2.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  url_launcher: ^6.2.4
  package_info_plus: ^9.0.0
  google_mobile_ads: ^6.0.0
  shared_preferences: ^2.2.2
  just_audio: ^0.10.5
  audio_session: ^0.2.2
  wakelock_plus: ^1.2.8
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.14.4
  in_app_purchase: ^3.1.11
  share_plus: ^10.0.0
  file_picker: ^8.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/sounds/
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: null
  adaptive_icon_foreground: "assets/icon.png"